### ISSUE TITLE
The Murder dont work

### ISSUE THREAD

**Issue by UnEnanoMas** [hamid0740/JobUI#12]
```Yaml
4:
  Name: "Asesino"
  Button-Name: "§cAsesino\n§4Matar jugadores"
  Image-Type: 0
  Image: "textures/items/diamond_sword"
  Info: "§6- §cAsesino§6:\n§dMisión:§g Asesinar a otros jugadores\n§bMatar jugadores §d[40$]"
  Permission: "jobui.job.asesino"
  Mode:
    Name: "Simple"
    Goal: 0
    Salary: 0
  Mission:
    Murderer: 50
```
```Yaml
---
Guest:
  alias: gst
  isDefault: true
  inheritance: []
  permissions:
  - jobui.job.*
  - jobui.job.asesino
```
