### ISSUE TITLE
help

### ISSUE THREAD

**Issue by x-lIlIlIlIl** [hamid0740/JobUI#9]
```Yaml
1:
  Name: "Tree Cutter"
  Button-Name: "§aTree Cutter"
  Image-Type: 0
  Image: "textures/blocks/log_oak"
  Info: "§6- §aTree Cutter§6:\n§dMission:\n§d(B)§bOak log §d[5$] (B)§bSpruce log §d[5$]\n§d(B)§bBirch log §d[5$] (B)§bJungle log §d[5$]\n§d(B)§bAcacia log §d[5$] (B)§bDark Oak log §d[5$]"
  Permission: "jobui.job.tree-cutter"
  Mode:
    Name: "Simple"
    Goal: 0
    Salary: 0
  Mission:
    17:0:Break: 5
    17:1:Break: 5
    17:2:Break: 5
    17:3:Break: 5
    17:4:Break: 5
    17:5:Break: 5
    17:6:Break: 5
    17:7:Break: 5
    17:8:Break: 5 
    17:9:Break: 5
    17:10:Break: 5
    17:11:Break: 5
    162:0:Break: 5
    162:1:Break: 5
    162:4:Break: 5
    162:5:Break: 5
    162:8:Break: 5
    162:9:Break: 5
2:
  Name: "Miner"
  Button-Name: "§3Miner"
  Image-Type: 0
  Image: "textures/blocks/coal_ore"
  Info: "§6- §3Miner§6:\n§dMission:\n§d(B)§bStone §d[3$] (B)§bCoal ore §d[10$]\n§d(B)§bIron ore §d[10$] (B)§bDiamond ore §d [15]\n§d(B)§bGold ore §d[15] (B)§bRedstone ore §d[15]\n§d(B)§dEmerald ore §b[25]"
  Permission: "jobui.job.miner"
  Mode:
    Name: "Simple"
    Goal: 0
    Salary: 0
  Mission:
    1:0:Break:  3
    16:0:Break: 10
    15:0:Break: 10
    56:0:Break: 15
    14:0:Break: 15
    73:0:Break: 15
    129:0:Break 25
3:
  Name: "Murderer"
  Button-Name: "§cMurderer\n§4Killing Players"
  Image-Type: 0
  Image: "textures/items/iron_axe"
  Info: "§6- §cMurderer§6:\n§dMission:\n§bKilling Players §d[50$]"
  Permission: "jobui.job.murderer"
  Mode:
    Name: "Simple"
    Goal: 0
    Salary: 0
  Mission:
    Murderer: 50
4:
  Name: "Tree Cutter Goal"
  Button-Name: "§aTree Cutter\n§dGoal"
  Image-Type: 0
  Image: "textures/blocks/log_oak"
  Info: "§6- §aTree Cutter(Goal Mode)§6:\n§dMission:\n§d(B)§bOak log§d, (B)§bSpruce log§d,\n§d(B)§bBirch log§d, (B)§bJungle log§d,\n§d(B)§bAcacia log§d, (B)§bDark Oak log\n§cGoal: §e20\n§cSalary: §e500"
  Permission: "jobui.job.tree-cutter-goal"
  Mode:
    Name: "Goal"
    Goal: 100
    Salary: 500
  Mission:
    17:0:Break: 0
    17:1:Break: 0
    17:2:Break: 0
    17:3:Break: 0
    17:4:Break: 0
    17:5:Break: 0
    17:6:Break: 0
    17:7:Break: 0
    17:8:Break: 0 
    17:9:Break: 0
    17:10:Break: 0
    17:11:Break: 0
    162:0:Break: 0
    162:1:Break: 0
    162:4:Break: 0
    162:5:Break: 0
    162:8:Break: 0
    162:9:Break: 0
5:
  Name: "Miner Goal"
  Button-Name: "§3Miner\n§dGoal"
  Image-Type: 0
  Image: "textures/blocks/coal_ore"
  Info: "§6- §3Miner(Goal Mode)§6:\n§dMission:\n§d(B)§bStone§d, (B)§bCoal ore§d,\n§d(B)§bIron ore\n§cGoal: §e20\n§cSalary: §e600"
  Permission: "jobui.job.miner-goal"
  Mode:
    Name: "Goal"
    Goal: 90
    Salary: 600
  Mission:
    1:0:Break:  0
    16:0:Break: 0
    15:0:Break: 0
    56:0:Break: 0
    14:0:Break: 0
    73:0:Break: 0
    129:0:Break 0
6:
  Name: "Murderer Goal"
  Button-Name: "§cMurderer\n§dGoal"
  Image-Type: 0
  Image: "textures/items/iron_axe"
  Info: "§6- §cMurderer(Goal Mode)§6:\n§dMission:\n§bKilling Players\n§cGoal: §e20\n§cSalary: §e1000"
  Permission: "jobui.job.murderer-goal"
  Mode:
    Name: "Goal"
    Goal: 200
    Salary: 1000
  Mission:
    Murderer: 0
...
```
See anything wrong here??? i been trying but it dont work :/
